function fevoHnwDashboard(pMsgApiUnavailable){this.tlrTimeout=[];this.msgApiUnavailable=pMsgApiUnavailable;}
function fevoHnwCommon(pPluginName,pApiAvailable,pShowHorizontal,pArgZoneId,pArgFileId,pEvoBackgroundColor,pEvoDefaultShowingScheduleMode,pEvoCmdBackgroundColor){this.C2BG=[[25,'#f21f1f'],[22,'#ff5b1a'],[19,'#fa9e2d'],[16,'#2e9985'],[0,'#247eb2']];this.imp='important';this.imp2=' !important';this.ScheduleCurrent='C';this.ScheduleSaved='S';this.pluginName=pPluginName;this.apiAvailable=pApiAvailable;this.showHorizontal=pShowHorizontal;this.argZoneId=pArgZoneId;this.argFileId=pArgFileId;this.evoBackgroundColor=pEvoBackgroundColor;this.generalLastMode=pEvoDefaultShowingScheduleMode;this.evoCmdBackgroundColor=pEvoCmdBackgroundColor;}
function evoShowMsgInfo(evoMsgInfo){if(evoMsgInfo!=''){var level='danger';if(evoMsgInfo.substring(0,1)==='1'){evoMsgInfo=evoMsgInfo.substring(1);level='success';}
$('#div_alert').showAlert({message:evoMsgInfo,level:level});}}
function evoRegisterHover(_id,_part){$('.hover'+_part+'ShowA'+_id).off().on('click',function(){evoFlipHover(_id,_part);});$('.hover'+_part+'ShowB'+_id).off().on('click',function(){evoHideHover(_id,_part);});}
function evoFlipHover(_id,part){var hoverShowB=$('.hover'+part+'ShowB'+_id);if(hoverShowB.is(":visible")){evoHideHover(_id,part);}else{hoverShowB.show();evoHnwDashboard.tlrTimeout[_id+part]=setTimeout(function(){hoverShowB.hide();},4000);}}
function evoHideHover(_id,part){$('.hover'+part+'ShowB'+_id).hide();clearTimeout(evoHnwDashboard.tlrTimeout[_id+part]);}
function initVarsCommon(pPluginName,_id,pEvoBackgroundColor,pEvoCmdBackgroundColor,pApiAvailable,pMsgApiUnavailable,pEvoDefaultShowingScheduleMode,pShowHorizontal,pArgZoneId,pArgFileId,pDashboardCssSize,pMsgInfo){if(typeof evoHnwCommon=='undefined'){$('#md_modal').on('dialogclose',function(){restoreCmdBgdColor();});window.evoHnwDashboard=new fevoHnwDashboard(pMsgApiUnavailable);window.evoHnwCommon=new fevoHnwCommon(pPluginName,pApiAvailable,pShowHorizontal,pArgZoneId,pArgFileId,pEvoBackgroundColor,pEvoDefaultShowingScheduleMode,pEvoCmdBackgroundColor);$('head').append('<link rel="stylesheet" type="text/css" href="plugins/'+pPluginName+'/core/template/dashboard/dashboard.css?'+pDashboardCssSize+'">');var _style="<style>"+".hoverTLRShow { display:none;padding:2px;position:absolute;left:50px;cursor:default;z-index:10;font-size:12px;white-space:nowrap;"+"background-color:"+pEvoBackgroundColor+";color:black;border:solid 1px black}"+".hoverTH .hoverTHShow { display:none;z-index:10;position:absolute;left:50px;top:-10px;width:320px;"+"text-align:left;font-size:12px;background-color:"+pEvoBackgroundColor+"}"+".TH2d1 { border-radius:3px;background-color:"+pEvoCmdBackgroundColor+"}"+".TH2d2 { border-radius:3px;background-color:"+pEvoCmdBackgroundColor+"}"+".btn.TH2d4 { display:block;padding-left:4px;padding-right:4px;padding-top:0px;padding-bottom:0px;"+"height:15px;min-width:18px !important;font-size:8px;line-height:15px;border-radius:2px;background-color:"+pEvoCmdBackgroundColor+" !important}"+".btn.TH2d5 { display:block;padding-left:2px;padding-right:2px;padding-top:0px;padding-bottom:0px;"+"height:15px;min-width:18px !important;font-size:8px;line-height:15px;border-radius:2px;background-color:"+pEvoCmdBackgroundColor+" !important}"+"</style>";$('head').append(_style);}
evoRegisterHover(_id,'TLR');evoShowMsgInfo(pMsgInfo);}
function checkApiAvailable(){if(!evoHnwCommon.apiAvailable){myAlert(evoHnwDashboard.msgApiUnavailable);return false;}
return true;}
function restoreCmdBgdColor(){setBgColor('.showCS',evoHnwCommon.evoCmdBackgroundColor);}
function waitingMessage(msg,params){bootbox.dialog({message:"<div class='text-center'>"+(params==null?msg:getMsg(msg,params))+"...</div>",closeButton:false});$('#md_modal').dialog('close');$('#jqueryLoadingDiv').show();}
function myAlert(msg,params){bootbox.alert({message:params==null?msg:getMsg(msg,params),closeButton:false});}
function myConfirm(msg,params){return confirm(params==null?msg:getMsg(msg,params));}
function boxConfirm(msg,callback){bootbox.confirm(msg,function(result){if(result){callback();}});}
function getMsg(msg,args){if(!is_array(args)){return msg.replace("{0}",args);}
for(var i=0;i<args.length;i++){msg=msg.replace("{"+i+"}",args[i]);}
return msg;}
function setColor(objName,color){$(objName).each(function(){this.style.removeProperty('color');this.style.setProperty('color',color,evoHnwCommon.imp);});}
function getBgColor(objName){return $(objName).css('background-color');}
function setBgColor(objName,color){$(objName).each(function(){this.style.removeProperty('background-color');this.style.setProperty('background-color',color,evoHnwCommon.imp);});}
function getBackColorForTemp(consigne){for(var p=0;p<5;p++){if(consigne>=evoHnwCommon.C2BG[p][0]){return evoHnwCommon.C2BG[p][1];}}
return evoHnwCommon.C2BG[4][1];}
evoHnwPubSub.p("db");