function fHnwConsole(pIsAdmin,pArgLocId,pArgCodeMode,pSetModeConfirm,pSetModeInfoList){this.genConsoleId=[];this.lastFileId=[];this.isCurrent=[];this.cmdSetModeId=[];this.cmdSaveId=[];this.isAdmin=pIsAdmin;this.argLocId=pArgLocId;this.argCodeMode=pArgCodeMode;this.setModeConfirm=pSetModeConfirm;this.setModeInfoList=pSetModeInfoList;}
function initVarsConsole(_locId,pArgLocId,_id,pIsAdmin,pScheduleFileId,pScheduleType,pCanRestoreCurrent,taskIsRunning,pTitleSetMode,pCodesAllowed,pModesArray,pSchedulesList,pEtatCode,pDisplaySetModeConsole,pCmdSetModeId,pArgCodeMode,pSetModeConfirm,pSetModeInfoList,pCmdSaveId,pSaveAs,pSaveInfoListMessage,pSaveReplace,pSaveName,pSaveRemark,pArgFileName,pArgFileRem,pCmdRestoreId,pRestoreConfirm,pRestoreInfoList,pCmdDeleteId,pDeleteConfirm,pDeleteInfoList,pLblSelectedProgram){if(typeof hnwConsole=='undefined'){window.hnwConsole=new fHnwConsole(pIsAdmin,pArgLocId,pArgCodeMode,pSetModeConfirm,pSetModeInfoList);}
hnwConsole.genConsoleId[_locId]=_id;hnwConsole.lastFileId[_id]=-1;hnwConsole.isCurrent[_id]=false;hnwConsole.cmdSetModeId[_id]=pCmdSetModeId;hnwConsole.cmdSaveId[_id]=pCmdSaveId;$('#md_modal').on('dialogclose',function(){hnwConsole.lastFileId[_id]=-1;});$('#scheduleList'+_id).on('change',function(){checkConsole(_id,pScheduleFileId,pCanRestoreCurrent,taskIsRunning);});checkConsole(_id,pScheduleFileId,pCanRestoreCurrent,taskIsRunning);if(pDisplaySetModeConsole=='1'&&pSchedulesList==null){$('.setMode'+_id).replaceWith(getModesTableIntegrated(_id,pModesArray,pCodesAllowed,pEtatCode));}else{$('.setMode'+_id).show();$('.popupSetMode'+_id).replaceWith(getModesTablePopup(_id,pModesArray,pCodesAllowed,pEtatCode,pSchedulesList,pLblSelectedProgram));if(pSchedulesList!=null){$('#cm'+_id+pEtatCode).click();}
if(!hnwCommon.apiAvailable)setBgColor('.setMode'+_id,'gray');}
$('#refresh'+_id).on('click',function(){var _data={action:'refresh'};_data[hnwConsole.argLocId]=_locId;$.ajax({type:'POST',url:'plugins/'+hnwCommon.pluginName+'/core/ajax/honeywell.ajax.php',dataType:'json',data:_data,error:function(request,status,error){handleAjaxError(request,status,error);}});});if(!taskIsRunning)$('#jqueryLoadingDiv').hide();else $('#jqueryLoadingDiv').show();$('.modal-backdrop').remove();$('.bootbox').remove();}
function checkConsole(id,pScheduleFileId,canRestoreCurrent,taskIsRunning){}
function getModesTableIntegrated(id,evoModes,codesAllowed,etatCode){var buttons='';for(var i=0;i<evoModes.length;i++){if(codesAllowed.indexOf(evoModes[i][0])!=-1){buttons+='<span class="cmd cmd-widget"><a class="action ui-btn ui-mini ui-btn-inline ui-btn-raised"';if(etatCode!=evoModes[i][0]){buttons+=' style="cursor:pointer;" onclick="setMode('+id+',1,'+evoModes[i][0]+',\''+evoModes[i][2]+'\');"';}else{buttons+=' style="cursor:default; color:green !important;"';}
buttons+='>';buttons+=evoModes[i][2];buttons+='</a></span>&nbsp;';}}
return buttons;}
function getModesTablePopup(id,evoModes,codesAllowed,etatCode,schedulesList,lblSelectedProgram){var buttons='<div class="popupSetMode'+id+'">';buttons+='<div style="text-align:-webkit-center;"><table width="100%"><tr>';var _code,_img,_name,_size=36;for(var i=0;i<evoModes.length;i++){_code=evoModes[i][0];_img=evoModes[i][1];_name=evoModes[i][2];if(codesAllowed.indexOf(_code)!=-1){buttons+='<td style="text-align:center;width:'+(100/6)+'%;padding-top:8px;';var schList=evoModes[i][3]==null||schedulesList==null?'null':'\''+encodeURI(JSON.stringify(schedulesList[evoModes[i][3]]))+'\'';var onClick='onclick="changeSchedulesList('+id+','+_code+',\''+_name+'\''+','+schList+');"';if(etatCode!=_code){if(schedulesList==null){buttons+='cursor:pointer;" onclick="setMode('+id+',2,'+_code+',\''+_name+'\',0);">';}else{buttons+='"><input style="cursor:pointer;" type="radio" id="cm'+id+_code+'" name="chooseMode'+id+'" '+onClick;if(!evoModes[i][4]){buttons+=' disabled="true"';}
buttons+='>';}}else if(schedulesList!=null&&evoModes[i][4]){buttons+='"><input style="cursor:pointer;" type="radio" id="cm'+id+_code+'" '+onClick+' name="chooseMode'+id+'" checked="checked">';}else{buttons+='">';}
buttons+='<label for="cm'+id+_code+'">';var bgc=(etatCode==_code?'green':'lightgray')+hnwCommon.imp2+(evoModes[i][4]?';cursor:pointer':'');buttons+='<img style="height:'+_size+'px;width:'+_size+'px;background-color:'+bgc+';" src="plugins/'+hnwCommon.pluginName+'/img/'+_img+'"/>';buttons+='<br/><span style="font-weight:400;';if(evoModes[i][4])buttons+='cursor:pointer;';if(etatCode==_code)buttons+='background-color:green'+hnwCommon.imp2+';color:white'+hnwCommon.imp2+';';buttons+='">&nbsp;'+_name+'&nbsp;</span>';buttons+='</label>';buttons+='</td>';}}
buttons+='</tr></table></div>';if(schedulesList!=null){buttons+='<div id="showSchList'+id+'" style="padding-left:16px;padding-top:8px;padding-bottom:8px;font-weight:100 !important;">';buttons+=lblSelectedProgram+'&nbsp;&nbsp;&nbsp;';buttons+='<select id="schList'+id+'" style="color:var(--txt-color);width:146px;font-size:11px;padding:4px !important;"></select>';buttons+='</div>';$('.modeValid'+id).on('click',function(){var schId=window.hnwConsole.setMode_NoFile?null:$('#schList'+id).value();setMode(id,2,window.hnwConsole.setMode_Mode,window.hnwConsole.setMode_Name,schId);});$('.modeButtons'+id).show();}else{buttons+='<br/>';$('.modeButtons'+id).hide();}
buttons+='</div>';return buttons;}
function changeSchedulesList(id,mode,name,sList){window.hnwConsole.setMode_Mode=mode;window.hnwConsole.setMode_Name=name;window.hnwConsole.setMode_NoFile=sList==null;if(sList==null){$('#showSchList'+id).hide();}else{var options='';sList=JSON.parse(decodeURI(sList));for(var i=0;i<sList.length;i++){options+='<option value="'+sList[i][0]+'"';options+=' style="background-color:#efefef !important;color:black !important;"';options+='>'+sList[i][1]+'</option>';}
$('#schList'+id)[0].innerHTML=options;$('#showSchList'+id).show();}}
function setMode(id,showType,mode,name,schId){if(!checkApiAvailable())return;if(!hnwCommon.apiAvailable){myAlert("Fonction indisponible");return;}
if(myConfirm(hnwConsole.setModeConfirm,name)){if(showType==2){$('.modeClose'+id).click();}
waitingMessage(hnwConsole.setModeInfoList,name);var _value={};_value[hnwConsole.argCodeMode]=mode+(schId?'§'+schId:'');jeedom.cmd.execute({id:hnwConsole.cmdSetModeId[id],notify:true,value:_value});}}