$("#table_cmd").sortable({axis:"y",cursor:"move",items:".cmd",placeholder:"ui-state-highlight",tolerance:"intersect",forcePlaceholderSize:true});function addCmdToTable(_cmd){if(!isset(_cmd))var _cmd={configuration:{}};if(!isset(_cmd.configuration))_cmd.configuration={};if(_cmd.logicalId=="etat"){$("#_idSH").html('{{Afficher}}');}else if(_cmd.logicalId=="temperature"){$("#_idSH").html('{{Afficher}}'+"/"+'{{Historiser}}');}
var tr='<tr class="cmd" data-cmd_id="'+init(_cmd.id)+'">';tr+='<td>';tr+='<span class="cmdAttr" data-l1key="id"></span>';tr+='</td>';tr+='<td>';tr+='<span class="cmdAttr" data-l1key="name" style="width:140px;"></span>';tr+='</td>';tr+='<td>';tr+='<span class="cmdAttr" data-l1key="type">'+init(_cmd.type)+'</span>';tr+='<br/><span class="cmdAttr" data-l1key="subType">'+init(_cmd.subType)+'</span>';tr+='</td>';tr+='<td style="width:200px;">';if(_cmd.configuration['canBeVisible']=='1'){tr+='<span><input type="checkbox" class="cmdAttr" data-size="mini" data-l1key="isVisible" checked/> {{Afficher}}</span><br/>';}
if(_cmd.configuration['canBeHistorize']=='1'){tr+='<span><input type="checkbox" class="cmdAttr" data-l1key="isHistorized"/> {{Historiser}}</span><br/>';}
tr+='</td>';tr+='<td>';if(is_numeric(_cmd.id)){tr+='<a class="btn btn-default btn-xs cmdAction" data-action="configure"><i class="fa fa-cogs"></i></a> ';tr+='<a class="btn btn-default btn-xs cmdAction" data-action="test"><i class="fa fa-rss"></i> {{Tester}}</a>';}
tr+='</td>';tr+='</tr>';$('#table_cmd tbody').append(tr);$('#table_cmd tbody tr:last').setValues(_cmd,'.cmdAttr');if(isset(_cmd.type))$('#table_cmd tbody tr:last .cmdAttr[data-l1key=type]').value(init(_cmd.type));jeedom.cmd.changeType($('#table_cmd tbody tr:last'),init(_cmd.subType));}
var modelType=null;var settingLocationId=false;var settingZoneId=false;$('.hnwSystem').on('change',function(){log('hnwSystem.onChange('+$('.hnwSystem').value()+')');if($('#equId').value()=='')return;changeSystem($('.hnwSystem').value());});function changeSystem(hnwSystem){log('changeSystem C='+hnwSystem);var locationIdList=$('.locationIdList')[0];locationIdList.options.length=0;locationIdList.options[0]=new Option('{{lecture...}}',-2);locationIdList.options[0].selected=true;$.ajax({type:'POST',url:PluginPath+'/core/ajax/honeywell.ajax.php',data:{action:'ajaxListLocations',system:hnwSystem},dataType:'json',error:function(request,status,error){handleAjaxError(request,status,error);},success:function(data){if(data.state!='ok'){$('#div_alert').showAlert({message:data.result,level:'danger'});}else if(is_array(data.result.loc)){modelType=null;var idSelect=0;var locationId=$('.locationId').value();if(data.result.loc.length==0){locationIdList.options[1]=new Option('{{Défaut}}',-1);}else{data.result.loc.forEach(function(loc,idx){modelType=loc.modelType;if(loc.locationId==locationId){idSelect=locationIdList.options.length;}
locationIdList.options[locationIdList.options.length]=new Option(loc.name,loc.locationId);});}
locationIdList.options[idSelect].selected=true;$('.locationIdList').change();locationIdList.options[0].text='{{Aucun}}';}}});}
function cantEnterLocation(id){var ret=$('.hnwSystem').value()==null||$('.hnwSystem').value()==''||id==null||id==''||id==-2||settingLocationId;log('cantEnterLocation='+ret);return ret;}
$('.locationId').on('change',function(){var id=$(this).value();log('locationId.change('+id+')');if(cantEnterLocation(id))return;changeLocation();settingLocationId=true;$('.locationIdList').value(id);settingLocationId=false;});$('.locationIdList').on('change',function(){var id=$(this).value();log('locationIdList.change('+id+')');if(cantEnterLocation(id))return;changeLocation();settingLocationId=true;$('.locationId').value(id);settingLocationId=false;});function changeLocation(){var locId=$('.locationId').value();if(locId==null||locId==-2)return;var zoneIdList=$('.zoneIdList')[0];var hnwSystem=$('.hnwSystem').value();zoneIdList.options.length=0;zoneIdList.options[0]=new Option('{{lecture...}}',-100);zoneIdList.options[0].selected=true;$.ajax({type:'POST',url:PluginPath+'/core/ajax/honeywell.ajax.php',data:{action:'ajaxListLocations',system:hnwSystem},dataType:'json',error:function(request,status,error){handleAjaxError(request,status,error);},success:function(data){if(data.state!='ok'){$('#div_alert').showAlert({message:data.result,level:'danger'});}else if(is_array(data.result.loc)){var idSelect=0;var zoneId=$('.zoneId').value();modelType=null;data.result.loc.forEach(function(loc,idx){if(loc.locationId==locId){zoneIdList.options[1]=new Option('{{Console}}',locId);if(zoneId==locId){idSelect=1;}
modelType=loc.modelType;if(hnwSystem!='LYRIC'){loc.zones.forEach(function(zone,idx){if(zone.id==zoneId){idSelect=zoneIdList.options.length;}
zoneIdList.options[zoneIdList.options.length]=new Option(zone.name,zone.id);});}else{loc.devices.forEach(function(zone,idx){zoneIdList.options[zoneIdList.options.length]=new Option(zone.name+' ('+zone.deviceModel+')',zone.deviceID);if(zone.deviceID==zoneId){idSelect=zoneIdList.options.length-1;}});}}});zoneIdList.options[idSelect].selected=true;changeZone($('.zoneIdList').value());zoneIdList.options[0]=new Option('{{Aucune}}',-2);}}});}
function cantEnterZone(id){var ret=$('.locationId').value()==null||$('.locationId').value()==-2||settingZoneId||id==null||id==''||id==-100;log('cantEnterZone='+ret);return ret;}
$('.zoneId').on('change',function(){var id=$(this).value();log('zoneId.change('+id+')');if(cantEnterZone(id))return;changeZone(id);settingZoneId=true;$('.zoneIdList').value(id);settingZoneId=false;});$('.zoneIdList').on('change',function(){var id=$(this).value();log('zoneIdList.change('+id+')');if(cantEnterZone(id))return;changeZone(id);settingZoneId=true;$('.zoneId').value(id);settingZoneId=false;});function changeZone(idZone){var imgName=null;if(idZone!=null&&idZone!=-2){var hnwSystem=$('.hnwSystem').value();if(idZone==$('.locationId').value()){if(hnwSystem==SystemEvohome){imgName=modelType!=ModelTypeRound?'console.png':'round-console.png';}else if(hnwSystem==SystemLyric){imgName='tx-console.png';}}else if(hnwSystem==SystemEvohome){imgName=modelType!=ModelTypeRound?'hr92.png':'round-th.png';}else if(hnwSystem==SystemLyric){imgName='t6-th.png';}}
if(imgName!=null)$('.img_device').attr('src',PluginPath+'/img/'+imgName);}
$('.fa-arrow-circle-left').on('click',function(){$('.img_device').attr('src','core/img/no_image.gif');});function log(msg){}