function EvoSchedule(pluginName,pAdjData,pConsoleId){this.DM_BY_ZONE='Z';this.DM_BY_DAY='D';this.MAX_POINTS=6;this.adjData=pAdjData;this.pluginName=pluginName;this.sl='#scheduleList'+pConsoleId;this.zones=new Array();this.days=new Array();this.scheduleSource=null;this.currentPoint=null;this.editAvailable=null;this.edit=null;this.zoneId=null;this.scheduleOpenCmd=null;this.skipNextGoWith=false;this.currentDay=null;this.scheduleSelectedId=$(this.sl+' option:selected').value();this.scheduleSelectedName=this.scheduleSelectedId==0?"":$(this.sl+' option:selected').text();this.nDay=-1;this.displayMode=null;this.currentZone=null;this.sortedZones=null;this.isEditAvailable=function(){return!this.edit&&this.editAvailable&&$(this.sl).length>0;};this.openEdit=function(zoneId,nDay,isEdit,displayMode){$('#md_modal').dialog('close');$('.showCurrentSchedule'+this.scheduleSource+zoneId).css('background-color','rgb(16, 208, 16)');$('#md_modal').dialog({position:{my:'center top',at:'center top+50',of:window}});var cmd=this.scheduleOpenCmd.replace('_zoneId_',zoneId);cmd=cmd.replace('_edit_',isEdit);cmd=cmd.replace('_nDay_',nDay);cmd=cmd.replace('_displayMode_',displayMode);$('#md_modal').load(cmd).dialog('open');};this.buildDailySchedules=function(content){this.DailySchedules=content;}
this.schedulesToString=function(s){return JSON.stringify(s,function(k,v){if(k==="pointsORG")return undefined;return v;});};this.isZoneModified=function(zone){return zone.schedulesORG!=_evs.schedulesToString(zone.schedules);};this.Zone=function(zoneId,name,eqName,schedules){this.zoneId=zoneId+'';this.name=name;this.eqName=eqName;this.schedules=schedules;this.schedulesORG=_evs.schedulesToString(schedules);};this._S=function(day,points){return new this.S(day,points);}
this.S=function(day,points){this.day=day;this.points=points;this.pointsORG=JSON.stringify(points);};this.isDayModified=function(s){return s.pointsORG!=JSON.stringify(s.points);};this._P=function(temp,hour){return new this.P(temp,hour,false);}
this.P=function(temp,hour,virtual){this.temp=temp;this.hour=hour;this.virtual=virtual;};this.buildPoint=function(zn,ds,ip,day,hm,hmNext,temp,virtual){return{zn:zn,ds:ds,ip:ip,day:day,hm:hm,hmNext:hmNext,temp:temp,virtual:virtual};};this.getEvoCurrentDay=function(){var jsd=new Date().getDay();return jsd==0?6:--jsd;};this.isDayModifiedByAnyZone=function(d){var ret=false;this.zones.forEach(function(zone){if(_evs.isDayModified(zone.schedules[d]))ret=true;});return ret;};this.displayHTable=function(){if(this.currentDay==null){this.currentDay=this.nDay!=-1?this.nDay:this.getEvoCurrentDay();}
var sortedZones=new Array();this.zones.forEach(function(zone){sortedZones[sortedZones.length]={eqName:zone.eqName,id:zone.zoneId,zn:sortedZones.length,modified:_evs.isZoneModified(zone),fullZone:zone};});sortedZones.sort(function(a,b){a=a.eqName.toLowerCase();b=b.eqName.toLowerCase();return a<b?-1:a>b?1:0;});this.sortedZones=sortedZones;if(this.currentZone==null)this.currentZone=sortedZones[0].zn;var currentTime=new Date().toLocaleString();currentTime=currentTime.substring(currentTime.lastIndexOf(' ')+1);if(this.displayMode==this.DM_BY_ZONE){this.displayHTableByZone(currentTime);}else{this.displayHTableByDay(currentTime);}
if(this.zoneId!='0'||this.nDay!=-1)$('#md_modal').dialog('option','height',"auto");};this.displayHTableByDay=function(currentTime){var _table="";for(var dsDay=0;dsDay<7;dsDay++){if(this.nDay==-1||this.nDay==dsDay){_table+="<table class='_t1 tableCmd'>";_table+="<tr><td colspan=2 class='_t2'><table width=100%><tr><td nowrap class='_t3'>&nbsp;&nbsp;";if(this.edit){_table+="<select id='srcDay' class='lstZone' onchange='_evs.showDay(parseInt(this.value));'>";for(var d=0;d<7;d++){_table+="<option value='"+d+"'";if(this.currentDay==d)_table+=" selected";_table+=">"+this.days[d];if(this.isDayModifiedByAnyZone(d))_table+=" *";_table+="</option>";}
_table+="</select>";}else{_table+=this.days[dsDay];}
if(this.nDay==-1&&this.isEditAvailable()&&!this.edit){_table+="<a class='btn btn-success btn-sm _edit' onclick='_evs.openEdit(0,"+dsDay+",1,_evs.DM_BY_DAY);'>";_table+=this.lblEdit+'</a>';}else if(this.nDay!=-1&&this.edit){_table+='<a class="btn btn-primary btn-sm _t31" onclick="_evs.copyDay();">'+this.lblCopyTo+'</a>&nbsp;&nbsp;';}
_table+="</td>";_table+="</tr></table></td></tr>";for(var szn=0;szn<this.sortedZones.length;szn++){var mySortedZone=this.sortedZones[szn];var myZone=mySortedZone.fullZone;var zn=mySortedZone.zn;if(this.zoneId=='0'||this.zoneId==myZone.zoneId+''){for(var ids=0;ids<myZone.schedules.length;ids++){ds=myZone.schedules[ids];if(ds.day==dsDay){_table+="<tr>";_table+="<td id='row"+zn+"' nowrap='nowrap' class='";if(szn==this.sortedZones.length-1)_table+="_rowTdA";var actifZone=(this.currentPoint==null&&zn==this.currentZone)||(this.currentPoint!=null&&zn==this.currentPoint.zn);if(actifZone&&!this.edit)
_table+="_rowTdB";_table+="'>";if(this.edit){_table+="&nbsp;&nbsp;<input id='rzone"+zn+"' name='rzone' type='radio' value='"+zn+"'";if(actifZone)
_table+=" checked";_table+="/>";}
_table+="&nbsp;<label for='rzone"+zn+"'>"+myZone.eqName+"</label>&nbsp;&nbsp;";_table+="</td><td width=100%>";_table+="<table border=1 width=100% class='";_table+=!this.edit?"_t4":"_t4e";_table+="'>";_table+=this.getRowContent(zn,ids,ds,currentTime,"Zone");}}}}
_table+="</table>";if(!this.edit&&dsDay<7)_table+="<br/>";}}
document.getElementById('scheduleTable').innerHTML=_table;if(this.edit){$('input[name="rzone"]').on('click',function(event){_evs.currentZone=this.value;_evs.currentPoint=null;_evs.displayHTable();});if(this.currentPoint!=null)this.goWithForZone(this.currentPoint,0);}};this.displayHTableByZone=function(currentTime){var _table="";var inherited=null;for(var zn=0;zn<this.zones.length;zn++){myZone=this.zones[zn];if(this.zoneId=='0'||this.zoneId==myZone.zoneId+''){_table+='<table class="_t1 tableCmd">';_table+='<tr><td colspan=2 class="_t2"><table width=100%><tr><td nowrap class="_t3">&nbsp;&nbsp;';if(this.edit){_table+='<select id="srcZone" class="lstZone" onchange="_evs.showZone(parseInt(this.value));">';this.sortedZones.forEach(function(zone){_table+='<option value="'+zone.id+'"';if(_evs.zoneId==zone.id)
_table+=' selected';_table+='>'+zone.eqName;if(zone.modified)
_table+=' *';_table+='</option>';});_table+='</select>';}else{_table+=myZone.eqName;}
if(this.zoneId=='0'&&this.isEditAvailable()&&!this.edit){_table+='<a id="btnEdit'+myZone.zoneId+'" class="btn btn-success btn-sm _edit" onclick="_evs.openEdit(\''+myZone.zoneId+'\',-1,1,_evs.DM_BY_ZONE);">';_table+=this.lblEdit+'</a>';}else if(this.zoneId!='0'&&this.edit){_table+='<a class="btn btn-primary btn-sm _t31" onclick="_evs.copyZone();">'+this.lblCopyTo+'</a>&nbsp;&nbsp;';}
_table+="</td>";_table+="</tr></table>";_table+="</td></tr>";for(var ids=0;ids<myZone.schedules.length;ids++){ds=myZone.schedules[ids];_table+='<tr>';_table+='<td id="row'+ids+'" nowrap="nowrap" class="';if(ids==6)_table+='_rowTdA';var actifDay=(this.currentPoint==null&&ds.day==this.currentDay)||(this.currentPoint!=null&&ds.day==this.currentPoint.day);if(actifDay&&!this.edit)_table+='_rowTdB';_table+='">';if(this.edit){_table+="&nbsp;&nbsp;<input id='rday"+ds.day+"' name='rday' type='radio' value='"+ds.day+"'";if(actifDay)
_table+=" checked";_table+="/>";}
_table+="&nbsp;<label for='rday"+ds.day+"'>"+this.days[ds.day]+"</label>&nbsp;&nbsp;";_table+="</td><td width=100%>";_table+="<table border=1 width=100% class='";_table+=!this.edit?'_t4':'_t4e';_table+="'>";_table+=this.getRowContent(zn,ids,ds,currentTime,"Day");}
_table+="</table>";if(this.zoneId=='0'&&zn<this.zones.length)_table+="<br/>";}}
document.getElementById('scheduleTable').innerHTML=_table;if(this.edit){$('input[name="rday"]').on('click',function(event){_evs.currentDay=parseInt(this.value);_evs.currentPoint=null;_evs.displayHTable();});if(this.currentPoint!=null)this.goWithForDay(this.currentPoint,0);}};this.getRowContent=function(zn,ids,ds,currentTime,gwMode){var rowContent="<tr>";var mark=0;var hmNext=null;var te;for(var ip=1;ip<=ds.points.length;ip++){if(((gwMode=="Day"&&ds.day==this.currentDay)||(gwMode=="Zone"&&zn==this.currentZone))&&(ip==ds.points.length||ds.points[ip].hour.substr(0,5)>currentTime)){mark++;}
if(ip<ds.points.length){hmNext=ds.points[ip].hour.substr(0,5);te=parseInt(hmNext.substr(0,2)+hmNext.substr(3,2));}else{hmNext='-';te=2400;}
var sp=ds.points[ip-1];var hm=sp.hour.substr(0,5);rowContent+='<td ';var oPoint=this.buildPoint(zn,ids,ip-1,ds.day,hm,hmNext,sp.temp,sp.virtual);if(this.edit)rowContent+="onclick='_evs.goWithFor"+gwMode+"("+JSON.stringify(oPoint)+",1);'";var td=parseInt(hm.substr(0,2)+hm.substr(3,2));var _w=(te-td)/2400.0*100.0;rowContent+=' style="width:'+_w+'%;"><table border=0 width=100%>';if(gwMode=="Day"){rowContent+="<tr><td id=slice"+ids+"_"+(ip-1);if((((this.edit&&this.currentPoint==null)||!this.edit)&&mark==1)||(this.edit&&this.currentPoint!=null&&this.currentPoint.ds==ids&&this.currentPoint.ip==ip-1)){if(!this.edit)rowContent+=" class='_slice1'";if(this.currentPoint==null)this.currentPoint=oPoint;mark++;}else if(sp.virtual){rowContent+=" class='_slice2'";}}else{rowContent+="<tr><td id=slice"+zn+"_"+(ip-1);if((((this.edit&&this.currentPoint==null)||!this.edit)&&mark==1)||(this.edit&&this.currentPoint!=null&&this.currentPoint.zn==zn&&this.currentPoint.ip==ip-1)){if(!this.edit)rowContent+=" class='_slice1'";if(this.currentPoint==null)this.currentPoint=oPoint;mark++;}else if(sp.virtual){rowContent+=" class='_slice2'";}}
rowContent+='>'+hm+'</td></tr>';var bgc=sp.virtual?'#F0F0F0':getBackColorForTemp(sp.temp);rowContent+='<tr><td style="color:white;background-color:'+bgc+';"';if(this.edit||sp.virtual)rowContent+=' nowrap="nowrap"'
var sTemp=(sp.virtual?'<span class="fas fa-arrow-left _virtual" title="'+this.lblInheritTitle+'"/>':sp.temp.toFixed(1));rowContent+='>'+sTemp;if(this.edit&&!sp.virtual){rowContent+='&nbsp;<span class="fas fa-times removePoint" onclick="_evs.removePoint('+zn+','+ids+','+(ip-1)+');"/>';}
rowContent+='</td></tr></table>';}
rowContent+='</tr></table></td>';if(this.edit){rowContent+='<td nowrap style="width:20px;"';if(_evs.isDayModified(ds)){rowContent+=' class="_nocheck1" onclick="_evs.revert('+zn+','+ids+');">';rowContent+='&nbsp;<img class="_nocheck2" src="plugins/'+this.pluginName+'/img/reverse.png"/>';}else{rowContent+='>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';}
rowContent+='</td>';}
rowContent+='</tr>';return rowContent;};this.goWithForDay=function(op,mode){if(mode==1&&this.skipNextGoWith){this.skipNextGoWith=false;return;}
$('input[name="rday"][value="'+op.day+'"]').prop('checked',true);$("#row"+this.currentPoint.ds).css({'background-color':'','color':''});$("#slice"+this.currentPoint.ds+"_"+this.currentPoint.ip).css({'background-color':(this.currentPoint.virtual?'#F0F0F0':''),'color':(this.currentPoint.virtual?'gray':'')});$("#row"+op.day).css({'background-color':'lightgreen','color':'black'});$("#slice"+op.day+"_"+op.ip).css({'background-color':'lightgreen','color':'black'});this.currentDay=op.day;this.goWithCommon(op);};this.goWithForZone=function(op,mode){if(mode==1&&this.skipNextGoWith){this.skipNextGoWith=false;return;}
$('input[name="rzone"][value="'+op.zn+'"]').prop('checked',true);$("#row"+this.currentPoint.zn).css({'background-color':'','color':''});$("#slice"+this.currentPoint.zn+"_"+this.currentPoint.ip).css({'background-color':(this.currentPoint.virtual?'#F0F0F0':''),'color':(this.currentPoint.virtual?'gray':'')});$("#row"+op.zn).css({'background-color':'lightgreen','color':'black'});$("#slice"+op.zn+"_"+op.ip).css({'background-color':'lightgreen','color':'black'});this.currentZone=op.zn;this.goWithCommon(op);};this.goWithCommon=function(op){this.currentPoint=op;$('#setpoint').val("");$('#hours').val("");$('#minutes').val("");var atd=op.hm.split(":");setTimeout(function(){$('#setpoint').val(op.temp.toFixed(1));$('#hours').val(atd[0]);$('#minutes').val(atd[1]);_evs.checkAppendAndValid();},250);this.checkGoSlice();};this._VP=function(){return new this.P(0,"00:00:00",true);};this.showZone=function(idz){this.zoneId=idz+'';this.currentPoint=null;this.displayHTable();restoreCmdBgdColor();$('.showCurrentSchedule'+this.scheduleSource+idz).css('background-color','rgb(16, 208, 16)');};this.showDay=function(nDay){this.nDay=nDay;this.currentDay=null;this.currentPoint=null;this.displayHTable();}
this.removePoint=function(zn,ds,ip){this.skipNextGoWith=true;var points=this.zones[zn].schedules[ds].points;var pr=points[ip];if(myConfirm(ip<points.length-1?getMsg(this.lblRemovePoint,[pr.temp,pr.hour.substr(0,5),points[ip+1].hour.substr(0,5)]):getMsg(this.lblRemovePoint2,[pr.temp,pr.hour.substr(0,5)]))){points.splice(ip,1);if(points.length==0||(points.length>0&&points[0].hour!='00:00:00')){points.splice(0,0,this._VP());}
if(ip>0)ip--;var targetPoint=this.buildPoint(zn,ds,ip,this.zones[zn].schedules[ds].day,points[ip].hour,null,points[ip].temp,points[ip].virtual);if(this.nDay==-1){this.goWithForDay(targetPoint);}else{this.goWithForZone(targetPoint);}
this.displayHTable();}};this.revert=function(zn,ds){this.zones[zn].schedules[ds].points=JSON.parse(this.zones[zn].schedules[ds].pointsORG);if(this.currentPoint.zn==zn&&this.currentPoint.ds==ds){this.currentPoint=null;}
this.displayHTable();};this.getZoneId=function(){return this.displayMode==this.DM_BY_ZONE?this.zoneId:_evs.zones[$('input[name="rzone"]:checked').val()].zoneId;};this.adjustSetpoint=function(step){var oldValue=parseFloat($('#setpoint').val().trim());var zoneId=this.getZoneId();var zstep=this.adjData[zoneId].step;var newVal=step==-1&&oldValue>this.adjData[zoneId].min?oldValue-zstep:step==1&&oldValue<this.adjData[zoneId].max?oldValue+zstep:oldValue;$('#setpoint').val(newVal.toFixed(1));};this.adjustHours=function(step){var oldValue=parseInt($('#hours').val().trim());var newVal=step==-1&&oldValue>0?oldValue-1:step==1&&oldValue<23?oldValue+1:oldValue;$('#hours').val(newVal<10?"0"+newVal:newVal);this.checkAppendAndValid();};this.adjustMinutes=function(step){var hours=parseInt($('#hours').val().trim());var oldValue=parseInt($('#minutes').val().trim());var newVal=oldValue;if(step==-1){if(oldValue>0){newVal=oldValue-10;}else if(hours>0){newVal=50;hours--;}}else
if(oldValue<50){newVal=oldValue+10;}else if(hours<23){newVal=0;hours++;}
if(oldValue!=newVal){$('#hours').val(hours<10?"0"+hours:hours);$('#minutes').val(newVal==0?"00":newVal);}
this.checkAppendAndValid();};this.getInputTime=function(){return $('#hours').val()+":"+$('#minutes').val()+":00";};this.getInputTemp=function(){return parseFloat($('#setpoint').val());};this.checkAppendAndValid=function(){var points=this.zones[this.currentPoint.zn].schedules[this.currentPoint.ds].points;var p=points[this.currentPoint.ip];var nbPointsDefined=points.length-(points[0].virtual?1:0);var appActivate=nbPointsDefined<this.MAX_POINTS;var valActivate=!p.virtual||nbPointsDefined<this.MAX_POINTS;for(var i=0;i<points.length;i++){if(points[i].hour==this.getInputTime()){appActivate=false;if(i!=this.currentPoint.ip)valActivate=false;}}
$('#btnAppend').attr('disabled',!appActivate);$('#btnValid').attr('disabled',!valActivate);return{appActivate:appActivate,valActivate:valActivate};};this.append=function(){if(!this.checkAppendAndValid().appActivate){return;}
var points=this.zones[this.currentPoint.zn].schedules[this.currentPoint.ds].points;var hm=this.getInputTime();var ip=points.length;for(var p=0;p<points.length;p++){if(points[p].hour>hm){ip=p;break;}}
var temp=this.getInputTemp();points.splice(ip,0,this._P(temp,hm));this.currentPoint.ip=ip;this.currentPoint.temp=temp;this.currentPoint.hm=hm;this.checkAppendAndValid();this.displayHTable();};this.validate=function(){if(!this.checkAppendAndValid().valActivate){return;}
var points=this.zones[this.currentPoint.zn].schedules[this.currentPoint.ds].points;var p=points[this.currentPoint.ip];p.temp=this.getInputTemp();var it=this.getInputTime();p.hour=it;p.virtual=false;if(this.currentPoint.ip==0&&p.hour!='00:00:00'){points.splice(0,0,this._VP());this.currentPoint.ip++;}else{points.sort(function(a,b){return parseInt(a.hour.replace(/:/g,""))-parseInt(b.hour.replace(/:/g,""));});for(var i=0;i<points.length;i++){if(points[i].hour==it){this.currentPoint.ip=i;break;}}}
this.currentPoint.temp=p.temp;this.currentPoint.hm=it;this.checkAppendAndValid();this.displayHTable();};this._checkCopy=function(objs){for(var i=0;i<objs.length;i++){if(objs[i].checked){return true;}}
return false;};this.clonePoints=function(pSrc){var pDst=[];pSrc.forEach(function(ps){pDst[pDst.length]=new _evs.P(ps.temp,ps.hour,ps.virtual);});return pDst;};this.checkGoSlice=function(){var canPrevious=this.currentPoint.ip!=0;$('#prevSlice').attr('disabled',!canPrevious);var points=this.zones[this.currentPoint.zn].schedules[this.currentPoint.ds].points;var canNext=this.currentPoint.ip!=points.length-1;$('#nextSlice').attr('disabled',!canNext);return{canPrevious:canPrevious,canNext:canNext};};this.goSlice=function(step){var canPN=this.checkGoSlice();if((step==-1&&!canPN.canPrevious)||(step==1&&!canPN.canNext)){return;}
var newIp=this.currentPoint.ip+step;var ep=this.zones[this.currentPoint.zn].schedules[this.currentPoint.ds].points[newIp];var newPoint=this.buildPoint(this.currentPoint.zn,this.currentPoint.ds,newIp,this.currentPoint.day,ep.hour,null,ep.temp,ep.virtual);if(this.nDay==-1){this.goWithForDay(newPoint,0);}else{this.goWithForZone(newPoint,0);}};this.copyZone=function(){var srcZoneName=$('#srcZone option:selected').text();var options=[];for(var d=0;d<7;d++){var caption='  '+this.days[d];if(d==_evs.currentDay){caption+=' (source : '+srcZoneName+')';}
options[d]={text:caption,value:d+''};}
var dialog=bootbox.prompt({title:getMsg(_evs.lblCopyToTitle+' :',this.days[_evs.currentDay]+' / '+srcZoneName),inputType:'checkbox',inputOptions:options,buttons:{confirm:{label:_evs.lblValidate}},callback:function(choice){if(choice==null){return;}
var dstZones=$('input[name="dstZone"]:checked');var dtr=$('input[name="targetDays"]:checked');if(dtr.length==1&&dstZones.length==0){myAlert(_evs.lblCopyNoTarget);return false;}
var srcZone=null;for(var zn=0;zn<_evs.zones.length;zn++){if(_evs.zones[zn].zoneId==$('#srcZone').value()){srcZone=_evs.zones[zn];break;}}
var srcPoints=srcZone.schedules[_evs.currentDay].points;for(var i=0;i<dtr.length;i++){for(var iz=0;iz<dstZones.length;iz++){var dstZone=_evs.zones[dstZones[iz].value];if(dstZone.schedules[dtr[i].value].points!=srcPoints){dstZone.schedules[dtr[i].value].points=_evs.clonePoints(srcPoints);}}}
_evs.displayHTable();}});dialog.init(function(){$('.bootbox-form').prepend(_evs.lblCopyTargetDays+' :');$('.bootbox-input-checkbox').attr('name','targetDays');$('input[name="targetDays"][value='+_evs.currentDay+']').prop('checked',true);$('input[name="targetDays"][value='+_evs.currentDay+']').attr('disabled',true);var choices='';_evs.sortedZones.forEach(function(zone){choices+='<div class="checkbox"><label>';choices+='<input type="checkbox" name="dstZone" value="'+zone.zn+'"';if($('#srcZone option:selected').value()==zone.id){choices+=' checked disabled';}
choices+='/>'+zone.eqName+(zone.modified?' *':'');if($('#srcZone').value()==zone.id){choices+=' (source = '+_evs.days[_evs.currentDay]+')';}
choices+='</label></div>';});$('.bootbox-form').append('<br/>'+getMsg(_evs.lblCopyTargetZones)+' :'+choices);});};this.copyDay=function(){var srcDay=$('#srcDay').value();var srcZoneZn=$('input[name="rzone"]:checked')[0].value;var options=[];for(var d=0;d<7;d++){var caption='  '+$('#srcDay')[0].options[d].text;if(d==srcDay){caption+=' (source : '+_evs.zones[srcZoneZn].eqName+')';}
options[options.length]={text:caption,value:d+''};}
var dialog=bootbox.prompt({title:getMsg(_evs.lblCopyToTitle+' :',$('#srcDay option:selected').text()+' / '+_evs.zones[srcZoneZn].eqName),inputType:'checkbox',inputOptions:options,buttons:{confirm:{label:_evs.lblValidate}},callback:function(choice){if(choice==null){return;}
var dtr=$('input[name="targetDays"]:checked');var dstZone=$('input[name="dstZone"]:checked');if(dtr.length==1&&dstZone.length==0){myAlert(_evs.lblCopyNoTargetDay);return false;}
var srcPoints=_evs.zones[srcZoneZn].schedules[srcDay].points;for(var i=0;i<dtr.length;i++){for(var iz=0;iz<dstZone.length;iz++){_evs.zones[dstZone[iz].value].schedules[dtr[i].value].points=_evs.clonePoints(srcPoints);}}
_evs.displayHTable();}});dialog.init(function(){$('.bootbox-form').prepend(_evs.lblCopyTargetDays+' :');$('.bootbox-input-checkbox').attr('name','targetDays');$('input[name="targetDays"][value='+srcDay+']').prop('checked',true);$('input[name="targetDays"][value='+srcDay+']').attr('disabled',true);var choices='';_evs.sortedZones.forEach(function(zone){choices+='<div class="checkbox"><label>';choices+='<input type="checkbox" name="dstZone" value="'+zone.zn+'"';if(srcZoneZn==zone.zn)choices+=' checked disabled';choices+='/>'+zone.eqName+(zone.modified?' *':'');if(_evs.currentZone==zone.zn){choices+=' (source = '+_evs.days[_evs.currentDay]+')';}
choices+='</label></div>';});$('.bootbox-form').append(getMsg(_evs.lblCopyTargetZones)+' :'+choices);});};this.saveSchedule=function(){var fileName=$('#saveName').val().trim();if(fileName.length===0){myAlert(this.lblFileNameEmpty);return;}
var fileId=0;if(!(this.scheduleSelectedName===fileName)){$(this.sl+' option').each(function(){if(this.text===fileName){fileId=myConfirm(getMsg(_evs.lblReplaceSave,fileName))?this.value:-1;}});if(fileId==0&&!myConfirm(getMsg(this.lblCreate,fileName))){fileId=-1;}}else{fileId=myConfirm(getMsg(this.lblConfirmSave,fileName))?this.scheduleSelectedId:-1;}
if(fileId==-1){return;}
var scheduleToSave=JSON.stringify(_evs.zones,function(k,v){if(k==="schedules")
return new _evs.buildDailySchedules(v);if(k==="points"){var noVirtual=new Array();for(var i=0;i<v.length;i++)
if(!v[i].virtual){noVirtual[noVirtual.length]=v[i];}
return noVirtual;}
if(k==='eqName'||k==="virtual"||k==="schedulesORG"||k==="pointsORG"){return undefined;}
return v;}).replace(/id/g,"zoneId").replace(/schedules/g,"schedule").replace(/day/g,"DayOfWeek").replace(/points/g,"Switchpoints").replace(/temp/g,"heatSetpoint").replace(/hour/g,"TimeOfDay");evohomeSave(fileId,fileName,encodeURIComponent($('#idComment').val()),scheduleToSave);};}